import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from './_components/theme.provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfólio ",
  description: "Generated by create next app",
  keywords: ["Next.js", "Next", "Typescript", "Javacript", "React", "Tailwind", "Full-stack"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
